export const DIFFICULTY_LEVELS = {
  BEGINNER: 1,
  INTERMEDIATE: 2,
  ADVANCED: 3,
}

export const DIFFICULTY_MAP = {
  beginner: DIFFICULTY_LEVELS.BEGINNER,
  intermediate: DIFFICULTY_LEVELS.INTERMEDIATE,
  advanced: DIFFICULTY_LEVELS.ADVANCED,
}

export const REVERSE_DIFFICULTY_MAP = {
  [DIFFICULTY_LEVELS.BEGINNER]: "beginner",
  [DIFFICULTY_LEVELS.INTERMEDIATE]: "intermediate",
  [DIFFICULTY_LEVELS.ADVANCED]: "advanced",
}
